name: Windows CRD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 350

    steps:
    - name: Install Chrome
      run: |
        Invoke-WebRequest "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile chrome.exe
        Start-Process .\chrome.exe -ArgumentList "/silent", "/install" -Wait

    - name: Install Chrome Remote Desktop
      run: |
        Invoke-WebRequest "https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb" -OutFile crd.deb
        Invoke-WebRequest "https://dl.google.com/support/chrome/remote-desktop/chromeremotedesktophost.msi" -OutFile crd.msi
        Start-Process msiexec.exe -ArgumentList "/i crd.msi /quiet /qn /norestart" -Wait

    - name: Enable CRD Host
      run: |
        & "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="${{ secrets.CRD_CODE }}" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="GitHub-Windows"

    - name: Show CRD Link
      run: echo "Go to https://remotedesktop.google.com/access to connect."
